package com.escom.practica2.modelo;
// Generated 3/06/2015 12:37:11 AM by Hibernate Tools 3.6.0



/**
 * Calificacion generated by hbm2java
 */
public class Calificacion  implements java.io.Serializable {


     private Integer idcalificacion;
     private Alumno alumno;
     private Examen examen;
     private double puntaje;

    public Calificacion() {
    }

    public Calificacion(Alumno alumno, Examen examen, double puntaje) {
       this.alumno = alumno;
       this.examen = examen;
       this.puntaje = puntaje;
    }
   
    public Integer getIdcalificacion() {
        return this.idcalificacion;
    }
    
    public void setIdcalificacion(Integer idcalificacion) {
        this.idcalificacion = idcalificacion;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    public double getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(double puntaje) {
        this.puntaje = puntaje;
    }




}


