package com.escom.practica2.modelo;
// Generated 3/06/2015 04:00:34 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private Integer idcarrera;
     private Centrotrabajo centrotrabajo;
     private String nombre;
     private double duracion;
     private Set alumnos = new HashSet(0);

    public Carrera() {
    }

	
    public Carrera(Centrotrabajo centrotrabajo, String nombre, double duracion) {
        this.centrotrabajo = centrotrabajo;
        this.nombre = nombre;
        this.duracion = duracion;
    }
    public Carrera(Centrotrabajo centrotrabajo, String nombre, double duracion, Set alumnos) {
       this.centrotrabajo = centrotrabajo;
       this.nombre = nombre;
       this.duracion = duracion;
       this.alumnos = alumnos;
    }
   
    public Integer getIdcarrera() {
        return this.idcarrera;
    }
    
    public void setIdcarrera(Integer idcarrera) {
        this.idcarrera = idcarrera;
    }
    public Centrotrabajo getCentrotrabajo() {
        return this.centrotrabajo;
    }
    
    public void setCentrotrabajo(Centrotrabajo centrotrabajo) {
        this.centrotrabajo = centrotrabajo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public double getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(double duracion) {
        this.duracion = duracion;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }




}


