package com.escom.practica2.modelo;
// Generated 3/06/2015 04:00:34 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Examen generated by hbm2java
 */
public class Examen  implements java.io.Serializable {


     private Integer idexamen;
     private Materia materia;
     private String periodo;
     private Date fecha;
     private Set calificacions = new HashSet(0);
     private Set preguntas = new HashSet(0);

    public Examen() {
    }

	
    public Examen(Materia materia, String periodo, Date fecha) {
        this.materia = materia;
        this.periodo = periodo;
        this.fecha = fecha;
    }
    public Examen(Materia materia, String periodo, Date fecha, Set calificacions, Set preguntas) {
       this.materia = materia;
       this.periodo = periodo;
       this.fecha = fecha;
       this.calificacions = calificacions;
       this.preguntas = preguntas;
    }
   
    public Integer getIdexamen() {
        return this.idexamen;
    }
    
    public void setIdexamen(Integer idexamen) {
        this.idexamen = idexamen;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }
    
    public String toString(){
       return fecha.toString()+" "+periodo;
   }




}


