package com.escom.practica2.modelo;
// Generated 3/06/2015 12:37:11 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private Integer idmateria;
     private String nombre;
     private int creditos;
     private Set examens = new HashSet(0);

    public Materia() {
    }

	
    public Materia(String nombre, int creditos) {
        this.nombre = nombre;
        this.creditos = creditos;
    }
    public Materia(String nombre, int creditos, Set examens) {
       this.nombre = nombre;
       this.creditos = creditos;
       this.examens = examens;
    }
   
    public Integer getIdmateria() {
        return this.idmateria;
    }
    
    public void setIdmateria(Integer idmateria) {
        this.idmateria = idmateria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(int creditos) {
        this.creditos = creditos;
    }
    public Set getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set examens) {
        this.examens = examens;
    }




}


