package com.escom.practica2.modelo;
// Generated 3/06/2015 04:00:34 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private Integer idpregunta;
     private Examen examen;
     private String respuestaCorrecta;
     private String pregunta;
     private Set respuestas = new HashSet(0);

    public Pregunta() {
    }

	
    public Pregunta(Examen examen, String respuestaCorrecta, String pregunta) {
        this.examen = examen;
        this.respuestaCorrecta = respuestaCorrecta;
        this.pregunta = pregunta;
    }
    public Pregunta(Examen examen, String respuestaCorrecta, String pregunta, Set respuestas) {
       this.examen = examen;
       this.respuestaCorrecta = respuestaCorrecta;
       this.pregunta = pregunta;
       this.respuestas = respuestas;
    }
   
    public Integer getIdpregunta() {
        return this.idpregunta;
    }
    
    public void setIdpregunta(Integer idpregunta) {
        this.idpregunta = idpregunta;
    }
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    public String getRespuestaCorrecta() {
        return this.respuestaCorrecta;
    }
    
    public void setRespuestaCorrecta(String respuestaCorrecta) {
        this.respuestaCorrecta = respuestaCorrecta;
    }
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }
    public Set getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set respuestas) {
        this.respuestas = respuestas;
    }




}


