package com.escom.practica2.modelo;
// Generated 3/06/2015 04:00:34 PM by Hibernate Tools 3.6.0



/**
 * Respuesta generated by hbm2java
 */
public class Respuesta  implements java.io.Serializable {


     private Integer idrespuesta;
     private Pregunta pregunta;
     private String respuesta;

    public Respuesta() {
    }

    public Respuesta(Pregunta pregunta, String respuesta) {
       this.pregunta = pregunta;
       this.respuesta = respuesta;
    }
   
    public Integer getIdrespuesta() {
        return this.idrespuesta;
    }
    
    public void setIdrespuesta(Integer idrespuesta) {
        this.idrespuesta = idrespuesta;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }




}


