/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.escom.practica2.vista;

import com.escom.practica2.modelo.Examen;
import com.escom.practica2.modelo.Pregunta;
import com.escom.practica2.servicios.ExamenDaoCliente;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DARTH VADER
 */
public class ResultadosFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ResultadosFrame
     */
    public ResultadosFrame(List<Pregunta> listaPreguntas, String[] respuestas, int promedio) {
        initComponents();
//        System.out.println(promedio);
//        System.out.println(listaPreguntas.get(0).getPregunta());
//        System.out.println(respuestas[0]);
        listarArticulos(listaPreguntas,respuestas);
        prom.setText(promedio+"");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableResultados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        defe = new javax.swing.JLabel();
        prom = new javax.swing.JLabel();

        setClosable(true);
        setName("Resultados"); // NOI18N

        tableResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No. Pregunta", "Pregunta", "Tu Respuesta", "Respuesta Correcta", "Resultados"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableResultados);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Resultados");

        defe.setText("PROMEDIO");

        prom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prom.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(defe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prom)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defe, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prom))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel defe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel prom;
    private javax.swing.JTable tableResultados;
    // End of variables declaration//GEN-END:variables

    private void listarArticulos(List<Pregunta> listaPreguntas, String[] respuestas) {
        DefaultTableModel modelo = null;
        try {
            modelo = (DefaultTableModel) tableResultados.getModel();
            int a = modelo.getRowCount();
            for (int i = 0; i < a; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        String datos[] = new String[5];
        for (int i = 0; i < listaPreguntas.size(); i++) {
            datos[0] = Integer.toString(i+1);
            datos[1] = listaPreguntas.get(i).getPregunta();
            datos[2] = respuestas[i];
            datos[3] = listaPreguntas.get(i).getRespuestaCorrecta();
            if (respuestas[i] == null ? listaPreguntas.get(i).getRespuestaCorrecta() == null : respuestas[i].equals(listaPreguntas.get(i).getRespuestaCorrecta())) {
                datos[4]="Correcto";
            }else datos[4]="Error";
            
            modelo.addRow(datos);
        }

    }
}
